<?php
/**
 * Plugin Name: WP Dev Suit (must-use loader)
 * Description: Auto-generated by the WP Dev Suit plugin. Loads the mu-time part of each module. Do not edit — it is overwritten whenever the plugin updates.
 * Version: 1.0.0
 *
 * @package WP_Dev_Suit
 */

// Some tools have to start before the plugins they measure or patch, and a
// regular plugin cannot. This file is copied into mu-plugins on activation and
// does nothing itself except hand control to each module's mu.php.
//
// The {{...}} tokens are substituted with real values when the file is copied,
// so this keeps working if the plugin directory is renamed. Do not hardcode them.

defined( 'ABSPATH' ) || exit;

if ( defined( 'WPDS_MU_VERSION' ) ) {
	return;
}

define( 'WPDS_MU_VERSION', '1.0.0' );
define( 'WPDS_MU_MODULES_DIR', '{{MODULES_DIR}}' );

// Modules that filter the active plugin list need this to guarantee they can
// never switch the suite itself off, which would leave no way to switch it back.
define( 'WPDS_MU_SUITE_BASENAME', '{{SUITE_BASENAME}}' );

foreach ( (array) glob( WPDS_MU_MODULES_DIR . '/*/mu.php' ) as $wpds_mu_file ) {
	require_once $wpds_mu_file;
}

unset( $wpds_mu_file );
